/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bouncingball;

import java.awt.Color;
import java.awt.Graphics;
import java.security.SecureRandom;
import javax.swing.JPanel;

/**
 *
 * @author markoc
 */
public class DrawPanel extends JPanel{
    int ballCounter = 0;
    Ball[] balls = new Ball[30];
    Thread animation = new Thread(new Animation());
    /**
     * Creates new form DrawPanel
     */
    public DrawPanel() {
	initComponents();
	this.setBackground(Color.WHITE);
	animation.setDaemon(true);
    }
    
    public void addBall(int x, int y)
    {
	SecureRandom sr = new SecureRandom();
	
	this.balls[this.ballCounter] = new Ball(x, y, sr.nextInt(30)+100, sr.nextInt(30)+100, this.getHeight(), this.getWidth());
	this.ballCounter++;
    }
    
    @Override
    public void paintComponent(Graphics g){
	super.paintComponent(g);
	for(int i=0;i<balls.length;i++)
	{
	    if(balls[i] == null)
	    {
		g.dispose();
		break;
	    }
	    balls[i].paint(g);
	}
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
	if(!animation.isAlive())
	    animation.start();
	
	    addBall(evt.getX(), evt.getY());
    }//GEN-LAST:event_formMousePressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
	       
    }//GEN-LAST:event_formComponentShown

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        for(Ball ball : balls)
	{
	    if(ball == null)
		break;
	    ball.setPlaygroundHeight(this.getHeight()-(ball.getShadowHeight()/2));
	    ball.setPlaygroundWidth(this.getWidth()-(ball.getShadowHeight()/2));
	}
    }//GEN-LAST:event_formComponentResized

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded

    }//GEN-LAST:event_formComponentAdded

    class Animation implements Runnable
    {	
	@Override
	public void run() {		
	    while (true) {
                try {
                    Thread.sleep(40);
                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }
                repaint();
            }
	}
	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

